Property-Website/website/AvailableUnits/urls.py
from . import views
from django.urls import path
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

Property-Website/website/about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

Property-Website/website/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('home', views.home)
]

Property-Website/website/listings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.listings),
]

Property-Website/website/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login,),
    path("logout/", views.user_logout, name='logout'),
    path('register/', views.register, name='register')
]

Property-Website/website/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('myview/', views.myview, name='myview'),
    path('mycreate/', views.mycreate, name='mycreate')
]

Property-Website/website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('', include('AvailableUnits.urls')),
    path('listings/', include('listings.urls')),
    path('testing', include('AvailableUnits.urls')),
    path('about', include('about.urls')),
    path('login/', include('login.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Property-Website/website/AvailableUnits/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

# AVAILABLE = (
#      (0,"Available"),
#      (1,"Not Available")
# )

class Listings(models.Model):
    address = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=40, unique=True)
    content = models.TextField()
    pictures = models.ImageField(upload_to='images/',default='default.jpg')
    created_on = models.DateTimeField(auto_now_add=True)
    # available = models.IntegerField(choices=AVAILABLE, default=0)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.address

Property-Website/website/login/models.py
from django.db import models

# Create your models here.

Property-Website/website/myapp/models.py
from django.db import models

# Create your models here.

class MyModel(models.Model):
    myfield = models.CharField(max_length=200)

    
    
    def __str__(self):
        return self.myfield

Property-Website/website/AvailableUnits/views.py
from .models import Listings
from django.views.generic import ListView, DetailView
from django.shortcuts import render

# Create your views here.

class HomeView(ListView):
    model = Listings
    template_name = 'listings_list.html'

Property-Website/website/about/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    return render(request, 'about/about.html')

Property-Website/website/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

Property-Website/website/listings/views.py
# Create your views here.
from django.shortcuts import render

def listings(request):
    return render(request, 'listings/listings.html')

Property-Website/website/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid Login.')

    return render (request, 'login.html')

def user_logout(request):
    logout(request)
    return redirect('home')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created for {username}!')
            return redirect('login')
        
    else:
        form= UserCreationForm()
    return render(request,'register.html', {'form': form})

Property-Website/website/myapp/views.py
from django.shortcuts import render, reverse
from .models import MyModel
from django.http import HttpResponseRedirect

# Create your views here.

def myview(request):
    myinstances = MyModel.objects.all()
    context = {
        'myinstances': myinstances
    }
    return render(request, 'myapp/mytemplate.html', context)

def mycreate(request):
    myfield = request.POST['myfield']
    mymodel = MyModel(myfield=myfield)
    mymodel.save()
    return HttpResponseRedirect(reverse('myapp:myview'))

Property-Website/website/AvailableUnits/templates/availableunits/listings_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    body {
      background-repeat: no-repeat;
    
      background-size: cover; 

      overflow-y:auto
    }
  </style>
<head>
    
    <script src="{% static 'AvailableUnits/js/main.js' %}"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <!-- Listings -->
            <div class="col-12 text-center" style="font-family: 'Times New Roman'">
                {% for listing in object_list %}
                <ul>
                    <h1><u><a class="btn btn-outline-dark btn-lg bg-light bg-opacity-50" onclick='toggleContent({{forloop.counter}})'>{{listing.address}}</a></u></h1>
                    <div><img src="{{listing.pictures.url}}" style="background-color: black;"class="img-thumbnail border border-dark" alt="{{listing.address}}"></div>
                    <h2 id="listingContent{{ forloop.counter }}" style="display:none"><span class="bg-light bg-opacity-50 rounded">{{listing.content}}</span></h2>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
{%endblock%}

Property-Website/website/AvailableUnits/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .background {
        background-image: url("https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2019/4/16/1/HUHH2019-Waterfront_Jensen-Beach-FL_34.jpg.rend.hgtvcom.966.725.suffix/1555428341787.jpeg");
        background-position: bottom;
        background-repeat: no-repeat;
        background-size: cover;
        height: 100vh;
        width: 100%;
      }  
    </style>
    <title>Document</title>
</head>
<body class="bg-dark-subtle background">


    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">

            <a class="navbar-brand" style="font-family:'Times New Roman', Times, serif" href="http://127.0.0.1:8000/testing">Dependable Properties</a>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-link">
                  <a class="nav-link" style="font-family:'Times New Roman', Times, serif" href=http://127.0.0.1:8000/about>About us</a>
                </li>
              </ul>

              <a class="navbar" href="http://127.0.0.1:8000/admin">Login</a>
        
            

        </nav>
{%  block content %}

{% endblock content %}

</body>
</html>

Property-Website/website/about/templates/about/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>

<html>

<head>

<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'about.css' %}">
<style>
  body {
    background-repeat: no-repeat;
  
    background-size: cover; 
  }
</style>
<title>About Page</title>

</head>

<body>

<!-- Start your code here -->

<div class="container">

<div class="row">

   <div class="col-12 bg-light bg-opacity-50 rounded">

      <h1 class="text- text-center"style="font-family:'Times New Roman'"><span>What is Dependable Properties?</span></h1>

        <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>Dependable Properties is a family-owned property management business that prides itself on providing reliable and professional services to their clients. With years of experience in the industry, this company has built a reputation for exceptional customer service and attention to detail. They understand the importance of treating every property as if it were their own, and they work tirelessly to ensure that their clients receive the highest level of care and attention. Dependable Properties is committed to maintaining open lines of communication with their clients and providing personalized solutions to meet their unique needs. With a family-oriented approach to business, Dependable Properties is dedicated to building long-lasting relationships with their clients based on trust, integrity, and a commitment to excellence.</span></h2>

      <h1 class="text-black text-center" style="font-family:'Times New Roman'"><span>What are the requirements?</span></h1>
        <ul>
          <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>1) Your monthly income must be at least three times the monthly lease payments</span></h2>
          <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>2) No evictions in the last 10 years</span></h2>
          <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>3) No violent or illicit drug felonies in the last 10 years</span></h2>
          <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>4) If you fill out a application, pay the application fee and are approved and the unit you requested is no longer available we will refund your application fee or apply it to another available unit at your discretion. If you are not approved there is no refund.</span></h2>
          <h2 class="text-black text-center"style="font-family:'Times New Roman'"><span>5) We do check everything on your application. Your payment covers the fees associated with verification of your application.</span></h2>
        </ul>
    </div>

  </div>

</div>
{%endblock%}

Property-Website/website/home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <!-- This is the navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme = "dark">
        <div class="container-fluid">

            <a class="navbar-brand">Dependable Properties</a>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                  <a class="nav-link active">About us</a>
                </li>
              </ul>

              <a class="navbar">Login/Register</a>
        
            

        </nav>
    <h1>Hello This is my home page!</h1>
</body>
</html>

Property-Website/website/listings/templates/listings/listings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello Listings!</h1>
</body>
</html>

Property-Website/website/login/templates/login.html
{% extends 'base.html' %}
{% block content %}

    <h2>Login</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" id="password">
        </div>
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'register' %}">Register</a>

{% endblock %}

Property-Website/website/login/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

Property-Website/website/myapp/templates/myapp/mytemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'myapp:mycreate' %}" method="post">
        {% csrf_token %}
        <input type="text" name="myfield"/>
        <button type="submit">submit</button>
    </form>

    <ul>
        {% for myinstance in myinstances %}
        <li>{{ myinstance.myfield }}</li>
        {% endfor %}
      </ul>
</body>
</html>

Property-Website/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <!-- This is the navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">

            <a class="navbar-brand" style="font-family:'Times New Roman', Times, serif" href="http://127.0.0.1:8000/testing">Dependable Properties</a>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-link">
                  <a class="nav-link" style="font-family:'Times New Roman', Times, serif" href=http://127.0.0.1:8000/about>About us</a>
                </li>
              </ul>

              <a class="navbar" href="http://127.0.0.1:8000/admin">Login</a>
        
            

        </nav>

{%  block content %}
<!-- content goes here -->
{% endblock content %}

</body>
</html>